const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const code=fs.readFileSync(process.env.AUDIO_SOURCE||'web/js/gallery-music.js','utf8');
const settle=async()=>{for(let i=0;i<10;i++)await new Promise(setImmediate);};
function harness(settings={muted:false,volume:.8,effects:.7},native=false,delayPlay=false){
 const listeners=new Map(),elements=new Map(),saved=new Map([['quiet-stacks.music.v1',JSON.stringify(settings)]]),stats={contexts:0,plays:0,rejected:0,starts:0,resumes:0,mediaSources:0},contexts=[];let activation=false,mediaUnlocked=native,audio,time=0;
 function on(name,fn){if(!listeners.has(name))listeners.set(name,[]);listeners.get(name).push(fn);}
 const document={hidden:false,addEventListener:on,getElementById:id=>{if(!elements.has(id))elements.set(id,{value:'',setAttribute(){},addEventListener(){},showModal(){},close(){}});return elements.get(id);}};
 const completions=[];
 class Audio{constructor(){audio=this;this.paused=true;this.currentTime=0;this.listeners={};}addEventListener(n,f){this.listeners[n]=f;}play(){stats.plays++;if(!mediaUnlocked&&!activation){stats.rejected++;return Promise.reject(new Error('NotAllowed'));}mediaUnlocked=true;this.paused=false;return delayPlay?new Promise(resolve=>completions.push(resolve)):Promise.resolve();}pause(){this.paused=true;}}
 const node=()=>({connect(){},disconnect(){},gain:{value:0,cancelScheduledValues(){},setValueAtTime(v){this.value=v;},linearRampToValueAtTime(v){this.value=v;}}});
 class AudioContext{constructor(){stats.contexts++;contexts.push(this);this.state='suspended';this.currentTime=0;this.destination={};this.listeners={};this.enabled=native;}addEventListener(n,f){this.listeners[n]=f;}resume(){stats.resumes++;if(activation)this.enabled=true;if(!this.enabled)return Promise.reject(new Error('Gesture required'));this.state='running';queueMicrotask(()=>this.listeners.statechange?.());return Promise.resolve();}suspend(){this.state='suspended';return Promise.resolve();}createGain(){return node();}createMediaElementSource(){stats.mediaSources++;return node();}decodeAudioData(){return Promise.resolve({});}createBufferSource(){const n={...node(),playbackRate:{value:1},start(){stats.starts++;},stop(){n.onended?.();}};return n;}}
 const s={document,Audio,AudioContext,location:{protocol:native?'quietstacks:':'https:'},localStorage:{getItem:k=>saved.get(k),setItem:(k,v)=>saved.set(k,v)},URL:{createObjectURL:()=> 'blob:music'},Blob,fetch:async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(2),blob:async()=>new Blob(['music'])}),performance:{now:()=>time},addEventListener:on,queueMicrotask,console};s.window=s;vm.runInNewContext(code,s);
 return {s,stats,contexts,completions,get audio(){return audio;},elements,saved,emit(name,event={}){for(const f of listeners.get(name)||[])f(event);},gesture(name='pointerdown',event={}){activation=true;for(const f of listeners.get(name)||[])f(event);activation=false;},advance(ms){time+=ms;}};
}
test('first normal library gesture starts music without touching volume or waiting for another gesture',async()=>{const t=harness();t.gesture();await settle();assert.equal(t.audio.paused,false);assert.equal(t.stats.rejected,0);assert.equal(t.stats.contexts,1);});
test('touch release activates audio even without a mouse-style pointerdown',async()=>{const t=harness();t.gesture('touchend');await settle();assert.equal(t.audio.paused,false);assert.equal(t.stats.contexts,1);});
test('native first frame starts saved music without synthetic interaction or volume changes',async()=>{const t=harness(undefined,true);await settle();t.s.GalleryAudio.ready?.();await settle();assert.equal(t.audio.paused,false);assert.equal(t.s.GalleryAudio.snapshot().musicGain,.8);assert.equal(t.stats.contexts,1);});
test('effects-only preferences resume after background independently of music mute',async()=>{const t=harness({muted:true,volume:.8,effects:.7});t.gesture();await settle();t.emit('gallery-background');await settle();assert.equal(t.contexts[0].state,'suspended');t.emit('gallery-foreground');await settle();assert.equal(t.contexts[0].state,'running');t.s.GalleryAudio.effect('floor');assert.equal(t.stats.starts,1);assert.equal(t.audio.paused,true);});
test('zero music and interrupted context can resume effects without changing settings',async()=>{const t=harness({muted:false,volume:0,effects:.2});t.gesture();await settle();t.contexts[0].state='interrupted';t.emit('gallery-foreground');await settle();assert.equal(t.contexts[0].state,'running');t.s.GalleryAudio.effect('place');assert.equal(t.stats.starts,1);assert.equal(t.audio.paused,true);});
test('high low and mute preferences survive cold starts; effects zero stays silent',async()=>{for(const p of [{muted:false,volume:.9,effects:.8},{muted:false,volume:.03,effects:.02},{muted:true,volume:.9,effects:0},{muted:false,volume:0,effects:0}]){const t=harness(p,true);await settle();t.s.GalleryAudio.ready?.();await settle();assert.equal(t.audio.paused,p.muted||p.volume===0);assert.deepEqual(JSON.parse(JSON.stringify(t.s.GalleryAudio.snapshot().settings)),p);t.s.GalleryAudio.effect('floor');assert.equal(t.stats.starts,p.effects?1:0);assert.deepEqual(JSON.parse(t.saved.get('quiet-stacks.music.v1')),p);}});
test('repeated pointer/click foreground notifications do not duplicate music sources or effects',async()=>{const t=harness();t.gesture();await settle();for(let i=0;i<5;i++){t.gesture('pointerup');t.gesture('click');t.emit('gallery-foreground');}await settle();assert.equal(t.stats.contexts,1);assert.equal(t.stats.mediaSources,1);assert.equal(t.stats.plays,1);t.s.GalleryAudio.effect('floor');assert.equal(t.stats.starts,1);t.emit('gallery-background');assert.equal(t.s.GalleryAudio.snapshot().voices,0);assert.equal(t.audio.paused,true);});
test('music restarts on foreground with stored gain and does not run while hidden',async()=>{const t=harness();t.gesture();await settle();t.emit('gallery-background');await settle();assert.equal(t.audio.paused,true);t.emit('gallery-foreground');await settle();assert.equal(t.audio.paused,false);assert.equal(t.s.GalleryAudio.snapshot().musicGain,.8);t.s.document.hidden=true;t.emit('visibilitychange');await settle();t.emit('gallery-foreground');assert.equal(t.audio.paused,true);});
test('an interrupted pending play cannot block the next foreground or clear its pending state',async()=>{const t=harness(undefined,true,true);await settle();t.s.GalleryAudio.ready();await settle();assert.equal(t.stats.plays,1);t.emit('gallery-background');t.emit('gallery-foreground');await settle();assert.equal(t.stats.plays,2);t.completions[0]();await settle();assert.equal(t.s.GalleryAudio.snapshot().pendingPlay,true);assert.equal(t.audio.paused,false);t.completions[1]();await settle();assert.equal(t.s.GalleryAudio.snapshot().pendingPlay,false);});
