const test=require('node:test'),assert=require('node:assert/strict');
const {Gallery,SERIES,SLOTS,TOTAL,CART_CAPACITY,floorAllowed}=require('../web/js/gallery-model.js');
test('all 525 books start on the floor with empty shelves and trolley',()=>{const m=new Gallery();assert.equal(TOTAL,525);assert.equal(SERIES.length,100);assert.ok(Gallery.valid(m.state));assert.ok(m.state.books.every(b=>b.place==='floor'&&b.pose==='upright'&&floorAllowed(b)));});
test('all books can be placed manually without losing identity',()=>{const m=new Gallery();for(let id=0;id<TOTAL;id++)assert.ok(m.move(id,'shelf',id));assert.equal(new Set(m.state.books.map(b=>b.slot)).size,TOTAL);assert.ok(Gallery.valid(m.state));});
test('occupied shelves and trolley capacity reject moves without mutation',()=>{const m=new Gallery();m.move(0,'shelf',0);let before=JSON.stringify(m.state);assert.equal(m.move(1,'shelf',0),false);assert.equal(JSON.stringify(m.state),before);for(let i=1;i<=CART_CAPACITY;i++)assert.ok(m.move(i,'cart'));before=JSON.stringify(m.state);assert.equal(m.move(13,'cart'),false);assert.equal(JSON.stringify(m.state),before);});
test('any empty shelf accepts a book without automatic classification',()=>{const m=new Gallery();assert.ok(m.move(0,'shelf',SERIES[1].start));assert.equal(m.book(0).slot,SERIES[1].start);for(const name of ['gather','shelve','rotate','correct','undo'])assert.equal(m[name],undefined);});
test('old horizontal saves become upright in their original slots without moving other books',()=>{const m=new Gallery();m.move(0,'shelf',0);m.move(3,'shelf',3);m.move(4,'cart');const old=JSON.parse(JSON.stringify(m.state));old.version=3;old.books[0].pose='flat';old.camera.zoom=4;const n=new Gallery();assert.ok(n.restore(old));assert.equal(n.state.version,4);assert.equal(n.book(0).pose,'upright');assert.equal(n.book(0).slot,0);assert.equal(n.book(3).slot,3);assert.equal(n.book(4).place,'cart');assert.equal(n.state.camera.zoom,4);assert.ok(n.move(1,'shelf',1));for(let id=5;id<TOTAL;id++){assert.equal(n.book(id).x,old.books[id].x);assert.equal(n.book(id).y,old.books[id].y);}});
test('current saves reject unsupported poses and duplicate slots',()=>{const m=new Gallery();m.move(0,'shelf',0);const before=JSON.stringify(m.state);for(const mutate of [s=>s.books[0].pose='flat',s=>s.books[0].pose='invisible',s=>{s.books[1].place='shelf';s.books[1].slot=0;},s=>s.books[1].volume=99]){const bad=JSON.parse(before);mutate(bad);assert.equal(m.restore(bad),false);assert.equal(JSON.stringify(m.state),before);}const n=new Gallery();assert.ok(n.restore(JSON.parse(before)));assert.deepEqual(n.state,m.state);});
test('manual moves between floor shelf and trolley preserve all books',()=>{const m=new Gallery(),p=m.book(0);for(let i=0;i<300;i++){const id=i*37%TOTAL;m.move(id,'shelf',id);if(i%3===0)m.move(id,'floor',-1,{x:p.x,y:p.y});assert.ok(Gallery.valid(m.state));}assert.equal(m.state.books.length,TOTAL);});
