const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
function harness(width=1280,height=636){const elements=new Map(),windowEvents=new Map(),tools=new Map(),timers=new Map(),data=new Map();let frame;
 const ctx=new Proxy({},{get:(o,key)=>o[key]??((...args)=>{for(const n of args)if(typeof n==='number')assert.ok(Number.isFinite(n),`Non-finite Canvas argument in ${key}`)})});
 class Element{constructor(){this.listeners={};this.children=[];this.value='';this.textContent='';this.classList={add(){},remove(){},toggle(){}};this.dataset={};this.hidden=false;this.disabled=false}getBoundingClientRect(){return {x:0,y:84,left:0,top:84,width,height}}getContext(){return ctx}addEventListener(type,fn){this.listeners[type]=fn}focus(){}setPointerCapture(){}setAttribute(k,v){this[k]=v}matches(){return false}replaceChildren(){this.children=[];this.value=''}append(o){this.children.push(o);if(!this.value)this.value=o.value}showModal(){this.open=true}close(){this.open=false}}
 const get=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id)};
 const sandbox={console,AbortController,setTimeout:fn=>{const id=timers.size+1;timers.set(id,fn);return id},clearTimeout:id=>timers.delete(id),requestAnimationFrame:fn=>{frame=fn;return 1},cancelAnimationFrame(){},ResizeObserver:class{constructor(fn){this.fn=fn}observe(){this.fn()}},document:{getElementById:get,createElement:()=>new Element(),querySelectorAll:()=>[],querySelector:()=>null,addEventListener(){},modelContext:{registerTool(tool){tools.set(tool.name,tool)}}},devicePixelRatio:2,matchMedia:()=>({matches:false}),localStorage:{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)},addEventListener:(k,f)=>{if(!windowEvents.has(k))windowEvents.set(k,[]);windowEvents.get(k).push(f)}};
 sandbox.window=sandbox;vm.createContext(sandbox);for(const file of ['model','renderer','game'])vm.runInContext(fs.readFileSync(path.join(__dirname,`../web/js/${file}.js`),'utf8'),sandbox,{filename:file+'.js'});
 const state=()=>JSON.parse(JSON.stringify(tools.get('read_library').execute({}))),canvas=get('canvas');
 const screen=p=>{const s=state();return [(p[0]-s.camera[0])*s.zoom+width/2,(p[1]-s.camera[1])*s.zoom+height/2]};
 const pointer=(type,p,id=1)=>canvas.listeners[type]({button:0,pointerId:id,clientX:p[0],clientY:p[1]+84,preventDefault(){}});
 const advance=()=>{for(let i=0;i<90;i++)frame(16.67*(i+1))};
 const model=()=>{const m=new sandbox.QuietModel.Library();m.restore(state());return m};
 return {state,model,screen,pointer,advance,elements,get,tools,data,windowEvents,timers,sandbox,width,height};
}
test('Web startup draws at desktop and phone dimensions with finite geometry',()=>{for(const [w,h] of [[1280,636],[852,265],[390,650]]){const harn=harness(w,h);harn.advance();assert.equal(Object.keys(harn.state().books).length,54);assert.equal(harn.get('count').textContent,'9 / 54 shelved')}});
test('Pointer drag places exact book on shelf; Undo restores all container orders',()=>{const h=harness(),m=h.model(),before=h.state(),r=m.rects().find(r=>r.key==='pile_1'),b=m.state.books[r.id],key=`shelf_${b.category}_${b.series}_1`,origin=m.origin(key),a=h.screen([r.x+r.w/2,r.y+r.h/2]),p=h.screen([origin[0]+130,origin[1]-45]);h.pointer('pointerdown',a);h.pointer('pointermove',p);h.pointer('pointerup',p);assert.equal(h.model().location(r.id),key);h.get('undo').onclick();assert.deepEqual(h.state().containers,before.containers)});
test('Tap book then tap cart works without dragging',()=>{const h=harness(),m=h.model(),r=m.rects().find(r=>r.key==='pile_1'),a=h.screen([r.x+r.w/2,r.y+r.h/2]),p=h.screen([m.origin('cart_0')[0]+180,m.origin('cart_0')[1]-40]);h.pointer('pointerdown',a);h.pointer('pointerup',a);assert.equal(h.get('put-back').hidden,false);h.pointer('pointerdown',p);h.pointer('pointerup',p);assert.equal(h.model().location(r.id),'cart_0');assert.equal(h.get('put-back').hidden,true)});
test('Two-finger pinch never drops a held book',()=>{const h=harness(),m=h.model(),r=m.rects().find(r=>r.key==='pile_1'),a=h.screen([r.x+30,r.y+10]);h.pointer('pointerdown',a);h.pointer('pointerup',a);const before=h.state();h.pointer('pointerdown',[400,200],1);h.pointer('pointerdown',[600,200],2);h.pointer('pointermove',[730,240],2);h.pointer('pointerup',[730,240],2);h.pointer('pointerup',[400,200],1);assert.deepEqual(h.state().containers,before.containers);assert.ok(h.state().zoom>before.zoom);assert.equal(h.get('put-back').hidden,false)});
test('Dragging the cart handle transports its books and supports Undo',()=>{const h=harness(),before=h.state(),p=h.screen([before.cart[0]+284,before.cart[1]-137]),q=[p[0]+80,p[1]];h.pointer('pointerdown',p);h.pointer('pointermove',q);h.pointer('pointerup',q);assert.ok(h.state().cart[0]>before.cart[0]);assert.deepEqual(h.state().containers.cart_0.books,before.containers.cart_0.books);h.get('undo').onclick();assert.deepEqual(h.state().cart,before.cart)});
test('Top shelf focus remains visible in phone play area',()=>{const h=harness(852,265),m=h.model(),r=m.containerRect('shelf_0_0_1'),p=h.screen([r.x+r.w/2,r.y+r.h/2]);h.pointer('pointerdown',p);h.pointer('pointerup',p);h.advance();const center=h.screen([r.x+r.w/2,r.y+r.h/2]);assert.ok(center[1]>0&&center[1]<h.height);assert.ok(h.state().zoom>1)});
test('Keyboard alternative places the same identity and updates visible count',()=>{const h=harness();h.get('book-list').onclick();h.get('choose-book').value='book_0_0_1';h.get('choose-place').value='shelf_0_0_1';h.get('choose-position').value='0';h.get('place-book').onclick();assert.equal(h.model().location('book_0_0_1'),'shelf_0_0_1');assert.match(h.get('list-message').textContent,/Placed/)});
test('Structured placement contract uses visible state and rejects invalid moves',()=>{const h=harness(),t=h.tools.get('place_library_book');assert.equal(t.inputSchema.required.length,2);const result=t.execute({bookId:'book_0_0_1',containerId:'shelf_0_0_1',index:0});assert.equal(result.saved,true);assert.equal(h.state().containers.shelf_0_0_1.books[0],'book_0_0_1');const before=h.state();assert.throws(()=>t.execute({bookId:'missing',containerId:'cart_0'}));assert.throws(()=>t.execute({bookId:123,containerId:'cart_0'}));assert.deepEqual(h.state(),before);assert.ok(h.data.has('quiet-stacks.web.v2'))});
