const {test}=require('node:test');const assert=require('node:assert/strict');
const {Library,SaveStore}=require('../web/js/model.js');
class MemoryStorage{constructor(){this.data=new Map()}getItem(k){return this.data.get(k)??null}setItem(k,v){this.data.set(k,String(v))}removeItem(k){this.data.delete(k)}}
test('Fresh room has 54 unique books and 9 on shelves',()=>{const m=new Library();assert.equal(Object.keys(m.state.books).length,54);assert.equal(m.count(),9);assert.ok(Library.valid(m.snapshot()))});
test('Drag model: pile to shelf, exact identity, one-step undo',()=>{const m=new Library(),id=m.state.containers.pile_1.books[0],before=m.snapshot();assert.ok(m.move(id,'shelf_0_0_1',0));assert.equal(m.location(id),'shelf_0_0_1');assert.ok(m.undo());assert.deepEqual(m.state,before)});
test('New pile and its removal are one undo transaction',()=>{const m=new Library(),id=m.state.containers.pile_1.books[0],before=m.snapshot();assert.ok(m.floor(id,[1500,1300]));assert.equal(m.state.containers[m.location(id)].kind,'pile');m.undo();assert.deepEqual(m.state,before)});
test('Cart motion preserves relative book order and can be undone',()=>{const m=new Library(),books=[...m.state.containers.cart_0.books],before=m.snapshot(),rect=m.rects().find(r=>r.id===books[0]);m.checkpoint();m.moveCart([1500,1100]);const moved=m.rects().find(r=>r.id===books[0]);assert.equal(moved.x-rect.x,360);assert.equal(moved.y-rect.y,190);assert.deepEqual(m.state.containers.cart_0.books,books);m.undo();assert.deepEqual(m.state,before)});
test('Capacity is physical width, rejects overflow without a transaction',()=>{const m=new Library(),key='shelf_0_0_1';for(const id of Object.keys(m.state.books))if(m.canPlace(id,key))m.move(id,key);const id=Object.keys(m.state.books).find(id=>m.location(id)!==key),before=m.snapshot(),undo=m.history.length;assert.equal(m.move(id,key),false);assert.deepEqual(m.state,before);assert.equal(m.history.length,undo);const first=m.state.containers[key].books[0];assert.ok(m.move(first,key,99));assert.equal(m.state.containers[key].books.at(-1),first)});
test('Piles have a ten-book limit and reject the eleventh',()=>{const m=new Library(),key=m.createPile([1300,1250]);for(const id of Object.keys(m.state.books).slice(0,10))assert.ok(m.move(id,key));const before=m.snapshot();assert.equal(m.move(Object.keys(m.state.books)[10],key),false);assert.deepEqual(m.state,before)});
test('Removing the last book removes its provisional pile',()=>{const m=new Library(),id=Object.keys(m.state.books)[0];m.floor(id,[1400,1250]);const key=m.location(id);m.move(id,'shelf_0_0_1');assert.equal(m.state.containers[key],undefined);m.undo();assert.deepEqual(m.state.containers[key].books,[id])});
test('Invalid floor coordinates and unknown identities preserve state',()=>{const m=new Library(),before=m.snapshot();for(const p of [[-1,900],[100,700],[2500,800],[100,NaN]])assert.equal(m.floor('book_0_0_1',p),false);assert.equal(m.move('missing','cart_0'),false);assert.equal(m.move('book_0_0_1','missing'),false);assert.equal(m.moveCart([NaN,1]),false);assert.deepEqual(m.state,before)});
test('Sorting a series keeps six individual books in volume order',()=>{const m=new Library(),key='shelf_1_2_1';for(let v=1;v<=6;v++)assert.ok(m.move(`book_1_2_${v}`,key,v-1));assert.deepEqual(m.state.containers[key].books.map(id=>m.state.books[id].volume),[1,2,3,4,5,6]);const r=m.rects().filter(r=>r.key===key);assert.ok(r.every((r,i,a)=>i===0||r.x>=a[i-1].x+a[i-1].w));assert.ok(Library.valid(m.state))});
test('Local save roundtrip keeps catalog, camera, cart and all orders',()=>{const m=new Library(),store=new SaveStore(new MemoryStorage());m.move('book_2_0_4','cart_0');m.floor('book_1_0_1',[1000,1300]);m.state.camera=[1150,820];m.state.zoom=1.5;assert.ok(store.save(m));const other=new Library();assert.equal(store.load(other),'loaded');assert.deepEqual(other.state,m.state)});
test('Corrupt primary recovers backup; next save does not overwrite good backup with corruption',()=>{const storage=new MemoryStorage(),store=new SaveStore(storage),m=new Library();store.save(m);store.save(m);storage.setItem(store.key,'broken');const other=new Library();assert.equal(store.load(other),'recovered');assert.ok(store.save(other));storage.setItem(store.key,'still broken');assert.equal(store.load(new Library()),'recovered')});
test('Unavailable storage reports failure without losing current room',()=>{const m=new Library(),store=new SaveStore({getItem(){throw Error('denied')},setItem(){throw Error('quota')},removeItem(){}}),before=m.snapshot();assert.equal(store.load(m),'new');assert.equal(store.save(m),false);assert.deepEqual(m.state,before)});
test('Validation rejects duplicates, missing books, malformed containers and altered identities',()=>{const source=new Library();for(const mutate of [s=>s.containers.cart_0.books.push(s.containers.cart_0.books[0]),s=>s.containers.cart_0.books.pop(),s=>s.books.book_0_0_1.title='other',s=>s.camera=[Infinity,0],s=>s.cart=[0,0],s=>s.version=99,s=>s.containers.shelf_0_0_0=null,s=>s.zoom=99,s=>s.next_pile=1]){const state=source.snapshot();mutate(state);assert.equal(Library.valid(state),false);assert.equal(source.restore(state),false)}});
test('600 deterministic mixed operations conserve every identity and container capacity',()=>{const m=new Library();let seed=81724;const rand=n=>{seed=(seed*1664525+1013904223)>>>0;return seed%n};for(let i=0;i<600;i++){const ids=Object.keys(m.state.books),keys=Object.keys(m.state.containers),id=ids[rand(ids.length)];if(i%7===0)m.floor(id,[100+rand(2200),810+rand(560)]);else if(i%9===0)m.undo();else m.move(id,keys[rand(keys.length)],rand(9));assert.ok(Library.valid(m.state),`operation ${i}`)}});
module.exports={MemoryStorage};
