const test=require('node:test'),assert=require('node:assert/strict'),m=require('../web/js/gallery-model.js'),old=require('./fixtures/gallery-v176.json');
test('960 existing identities and arbitrary placements migrate without resetting progress',()=>{
 for(const sorted of [false,true]){const input=structuredClone(old);for(const b of input.books)if(sorted||b.id%3===0){b.place='shelf';b.slot=959-b.id;}else if(b.id<18&&b.id%3===1)b.place='cart';input.camera={x:600,y:470,zoom:2.5};const before=structuredClone(input),g=new m.Gallery();assert(g.restore(input));assert.deepEqual(input,before);assert.deepEqual(g.state.books.slice(0,960).map(({cartSlot,...b})=>b),input.books);assert.deepEqual(g.cart().map(b=>b.cartSlot),g.cart().map((_,i)=>i));assert.deepEqual(g.state.camera,input.camera);assert.equal(g.state.books.length,1119);
 for(const b of g.state.books.slice(960)){assert.equal(b.place,'floor');assert.equal(b.slot,-1);assert(m.floorAllowed(b));assert(b.order>=input.nextOrder);assert.equal(m.SLOTS[b.id].series,b.series);}
 assert(m.Gallery.valid(g.state));const next=new m.Gallery();assert(next.restore(JSON.parse(JSON.stringify(g.state))));assert.deepEqual(next.state,g.state);}
});
test('malformed 960-book saves cannot migrate or alter the current state',()=>{for(const mutate of [s=>s.books[0].volume++,s=>s.books[0].series++,s=>s.books.pop(),s=>{s.books[0].place='shelf';s.books[0].slot=1000;},s=>{s.books[0].place='shelf';s.books[0].slot=0;s.books[1].place='shelf';s.books[1].slot=0;},s=>s.nextOrder=1]){const s=structuredClone(old);mutate(s);const g=new m.Gallery(),before=structuredClone(g.state);assert.equal(g.restore(s),false);assert.deepEqual(g.state,before);}});
test('all bay ends support pickup, exact replacement, wrong-rack placement and reload',()=>{const g=new m.Gallery();g.demoArrange('sort');for(const c of m.SERIES)for(const id of [c.slotIds[0],c.slotIds.at(-1)]){const s=m.SLOTS[id];assert(g.move(id,'floor',-1,{x:860,y:250}));assert(g.drop(id,{x:s.x,y:s.y-c.bookHeight/2}));assert.equal(g.book(id).slot,id);assert.equal(g.placement(id),'exact');}assert(m.Gallery.valid(g.state));const next=new m.Gallery();assert(next.restore(g.state));assert.deepEqual(next.state,g.state);});
test('the first 960 floor positions and every unselected old artwork remain unchanged',()=>{assert.deepEqual(m.SCATTER.slice(0,960),old.books.map(({x,y})=>({x,y})));const before=require('../artifacts/shelf-fit-20260921/gallery-volumes.js'),now=require('../web/js/gallery-volumes.js'),selected=new Set(require('../design/volume-selected-20260922/composed.json').map(x=>x.art+':'+x.volume));for(let art=0;art<before.bindings.length;art++)for(let i=0;i<before.bindings[art].length;i++){const current=now.bindings[art][i];if(art===0&&i>=4&&i<=6){assert(current.moonMasterRepair);assert.deepEqual(current.source.slice(2),before.bindings[0][0].source.slice(2));}else if(selected.has(art+':'+(i+1)))assert(current.selectedRepair);else assert.deepEqual(current,before.bindings[art][i]);}});
test('new whole-spine assets retain original dimensions and bypass destructive matte removal',()=>{const items=require('../design/shelf-fit-20260921/extracted.json'),v=require('../web/js/gallery-volumes.js'),selected=new Set(require('../design/volume-selected-20260922/composed.json').map(x=>x.art+':'+x.volume));assert.equal(items.length,159);for(const b of items){const sprite=v.bindings[b.art][b.volume-1],wasSelected=selected.has(b.art+':'+b.volume);assert(wasSelected?sprite.selectedRepair:sprite.shelfFit);assert(v.atlases[sprite.atlas].preprocessedAlpha);assert.deepEqual(sprite.source.slice(2),b.size);assert(b.wholeSpine);assert(b.rect.height>180);assert(b.rect.width/b.rect.height<.7);}});
