// Build immutable opening positions and a dense, balanced boundary search tree.
// Sampling affects only invalid drops; valid floor/table coordinates stay exact.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const file=path.join(__dirname,'../web/js/gallery-model.js');
const context={require:require('node:module').createRequire(file),module:{exports:{}}};
vm.createContext(context);
const scatterSource=`const SCATTER=[];let seed=19377;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
for(let i=0;i<TOTAL;i++){let candidate;for(let tries=0;tries<12000;tries++){const p={x:26+random()*(W-52),y:312+random()*(H-343)};if(!scatterAllowed(p)||!floorAllowed(p))continue;const spacing=tries<2500?19:tries<7000?14:8;if(SCATTER.every(q=>Math.hypot(q.x-p.x,q.y-p.y)>spacing)){candidate=p;break;}}
if(!candidate)throw new Error('Not enough clear floor for the catalogue');SCATTER.push(candidate);}`;
vm.runInContext(fs.readFileSync(file,'utf8').replace('const SCATTER=LAYOUT.scatter;',scatterSource).replace('const api={','const api={geometry:{FLOOR_REGIONS,TABLE_TOPS,SOLID_FURNITURE,OBSTACLES,FIXTURES},'),context);
const m=context.module.exports,g=m.geometry,points=[],seen=new Set();
const offsets=[[0,0],[.02,0],[-.02,0],[0,.02],[0,-.02],[.02,.02],[-.02,.02],[.02,-.02],[-.02,-.02]];
function sample(x,y){for(const [dx,dy] of offsets){const p={x:+(x+dx).toFixed(6),y:+(y+dy).toFixed(6)};if(!m.floorAllowed(p))continue;const key=p.x+','+p.y;if(!seen.has(key)){seen.add(key);points.push([p.x,p.y]);}return;}}
const polygons=[...g.FLOOR_REGIONS,...g.TABLE_TOPS,...g.SOLID_FURNITURE,
  ...g.OBSTACLES.slice(0,9).map(([x,y,w,h])=>[[x,y],[x+w,y],[x+w,y+h],[x,y+h]]),
  [[22,90],[m.W-22,90],[m.W-22,m.H-20],[22,m.H-20]]];
for(const poly of polygons)for(let i=0;i<poly.length;i++){
  const a=poly[i],b=poly[(i+1)%poly.length],steps=Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])/.5);
  for(let n=0;n<=steps;n++)sample(a[0]+(b[0]-a[0])*n/steps,a[1]+(b[1]-a[1])*n/steps);
}
for(const [x,y,rx,ry] of g.FIXTURES){const steps=Math.ceil(2*Math.PI*Math.max(rx,ry)/.5);for(let n=0;n<steps;n++){const a=n*2*Math.PI/steps;sample(x+Math.cos(a)*rx,y+Math.sin(a)*ry);}}
function tree(items,depth=0){if(!items.length)return [];const axis=depth%2;items.sort((a,b)=>a[axis]-b[axis]||a[1-axis]-b[1-axis]);const mid=items.length>>1;return [...tree(items.slice(0,mid),depth+1),items[mid],...tree(items.slice(mid+1),depth+1)];}
const data={spacing:.5,scatter:m.SCATTER,points:tree(points).flat()};
const output='// Generated by scripts/generate-layout.cjs. Rebuild after changing room geometry.\n(function(root){const layout='+JSON.stringify(data)+';if(typeof module!=="undefined")module.exports=layout;root.GalleryLayout=layout;})(typeof globalThis!=="undefined"?globalThis:this);\n';
fs.writeFileSync(path.join(__dirname,'../web/js/gallery-layout.js'),output);
console.log(JSON.stringify({boundaryPoints:points.length,bytes:Buffer.byteLength(output),scatter:data.scatter.length}));
