const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),sharp=require(process.env.SHARP_MODULE||'sharp');
const root=path.resolve(__dirname,'..'),out=path.join(root,'artifacts/performance-0167');fs.mkdirSync(out,{recursive:true});
(async()=>{const {default:files}=await import('../runtime-files.mjs');const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';if(!files.includes(name)){res.writeHead(404).end();return;}let data=fs.readFileSync(path.join(root,'web',name));if(name==='js/gallery.js')data=Buffer.from(data.toString().replace('const camera=()=>model.state.camera;','window.__qaModel=model;window.__qaDraw=requestDraw;const camera=()=>model.state.camera;'));res.writeHead(200,{'Content-Type':name.endsWith('.js')?'text/javascript':name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'image/png'});res.end(data);});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({executablePath:process.env.CHROME_EXECUTABLE,headless:true});const result={version:JSON.parse(fs.readFileSync('package.json')).version,platform:'Desktop Chrome, not iPhone',trials:[],visual:[]};
for(const backend of ['canvas2d','webgl']){const page=await browser.newPage({viewport:{width:724,height:354},deviceScaleFactor:2}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 if(backend==='canvas2d')await page.addInitScript(()=>Object.defineProperty(window,'GalleryGpu',{get:()=>undefined,set:()=>{}}));
 await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.__galleryRenderedFrames>0);assert.equal(await page.evaluate(()=>__galleryGraphics.backend),backend);await page.addStyleTag({content:'#gallery > :not(#scene){visibility:hidden!important}'});
 for(const mode of ['scatter','sort'])for(const zoom of [1,3.5,8]){await page.evaluate(({mode,zoom})=>{__qaModel.demoArrange(mode);Object.assign(__qaModel.state.camera,{x:836,y:470,zoom});__qaDraw();},{mode,zoom});await page.waitForTimeout(150);await page.locator('#scene').screenshot({path:path.join(out,backend+'-'+mode+'-'+zoom+'.png')});}
 await page.evaluate(()=>__qaModel.demoArrange('scatter'));
 for(const zoom of [1.2,3.5]){const sample=await page.evaluate(zoom=>new Promise(resolve=>{const t0=performance.now(),first=__galleryRenderedFrames,uploads=__galleryGraphics.textureUploads;function tick(t){if(t-t0>=2500){resolve({zoom,frames:__galleryRenderedFrames-first,duration:t-t0,fps:(__galleryRenderedFrames-first)*1000/(t-t0),graphics:__galleryGraphics,uploadsBefore:uploads});return;}Object.assign(__qaModel.state.camera,{zoom,x:836+Math.sin(t/600)*110,y:470+Math.cos(t/750)*70});__qaDraw();requestAnimationFrame(tick);}requestAnimationFrame(tick);}),zoom);if(backend==='webgl'){assert.equal(sample.graphics.textureUploads,sample.uploadsBefore);assert.ok(sample.graphics.drawCalls<=4);}result.trials.push({backend,...sample});}
 const idle=await page.evaluate(()=>__galleryRenderedFrames);await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>__galleryRenderedFrames),idle);
 if(backend==='webgl'){
  assert.equal(await page.evaluate(()=>document.getElementById('scene').getContext('webgl').getError()),0);
  const before=await page.evaluate(()=>__qaModel.state);await page.evaluate(()=>{window.__lose=document.getElementById('scene').getContext('webgl').getExtension('WEBGL_lose_context');__lose.loseContext();});await page.waitForTimeout(200);await page.evaluate(()=>__lose.restoreContext());await page.waitForFunction(n=>__galleryRenderedFrames>n,idle);assert.deepEqual(await page.evaluate(()=>__qaModel.state),before);assert.equal(await page.evaluate(()=>document.getElementById('scene').getContext('webgl').getError()),0);result.contextRestored=true;
 }
 assert.deepEqual(errors,[]);await page.close();}
for(const mode of ['scatter','sort'])for(const zoom of [1,3.5,8]){const a=await sharp(path.join(out,'canvas2d-'+mode+'-'+zoom+'.png')).removeAlpha().raw().toBuffer(),b=await sharp(path.join(out,'webgl-'+mode+'-'+zoom+'.png')).removeAlpha().raw().toBuffer();assert.equal(a.length,b.length);let total=0,large=0;for(let i=0;i<a.length;i++){const d=Math.abs(a[i]-b[i]);total+=d;if(d>40)large++;}const v={mode,zoom,meanChannelDifference:total/a.length,largeDifferenceFraction:large/a.length};result.visual.push(v);assert.ok(v.meanChannelDifference<8,'Large visual change: '+JSON.stringify(v));}
fs.writeFileSync(path.join(out,'gpu-verification.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
