(function(){'use strict';
const {Library,SaveStore,CATEGORIES,clamp}=QuietModel;
const $=id=>document.getElementById(id),canvas=$('canvas'),room=$('room');const model=new Library();
let storage;try{storage=window.localStorage}catch{storage={getItem:()=>null,setItem:()=>{throw Error('Storage unavailable')},removeItem:()=>{}}}
const saves=new SaveStore(storage),load=saves.load(model),renderer=new QuietRenderer(canvas);
const view={w:1,h:1,dpr:1,camera:[...model.state.camera],zoom:model.state.zoom,selected:'',pointer:[0,0],dragging:false,hints:true,hover:''};
let targetCamera=[...view.camera],targetZoom=view.zoom,gesture=null,suppress=false,pinch=null,saveTimer,toastTimer,frame=0,lastTime=0,sound=false,audio;
const pointers=new Map(),reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const contains=(r,p,pad=0)=>p[0]>=r.x-pad&&p[0]<=r.x+r.w+pad&&p[1]>=r.y-pad&&p[1]<=r.y+r.h+pad;
const world=p=>[(p[0]-view.w/2)/view.zoom+view.camera[0],(p[1]-view.h/2)/view.zoom+view.camera[1]];
const point=e=>{const r=canvas.getBoundingClientRect();return[e.clientX-r.left,e.clientY-r.top]};
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4200)}
function persist(){clearTimeout(saveTimer);model.state.camera=[...targetCamera];model.state.zoom=targetZoom;const ok=saves.save(model);$('save-status').textContent=ok?'Saved in this browser':'Could not save · keep this tab open';if(!ok)saveTimer=setTimeout(persist,5000);return ok}
function changed(){model.state.camera=[...targetCamera];model.state.zoom=targetZoom;$('save-status').textContent='Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(persist,350);hud()}
function hud(){const b=model.state.books[view.selected];$('count').textContent=`${model.count()} / 54 shelved`;$('undo').disabled=!model.history.length;$('put-back').hidden=!b;$('book-title').textContent=b?`${b.title} · Volume ${b.volume}`:'Make a little room.';$('book-detail').textContent=b?`${CATEGORIES[b.category]} · tap a shelf, cart, pile, or floor`:'Drag books · pan empty space · pinch to zoom';$('hints').setAttribute('aria-pressed',String(view.hints));$('hints').textContent=view.hints?'Hints on':'Hints off';$('sound').setAttribute('aria-pressed',String(sound))}
function clampCamera(){targetCamera=[clamp(targetCamera[0],160,2340),clamp(targetCamera[1],140,1370)];changed()}
function zoom(factor,p=[view.w/2,view.h/2]){const before=world(p);targetZoom=clamp(targetZoom*factor,.18,3.6);targetCamera=[before[0]-(p[0]-view.w/2)/targetZoom,before[1]-(p[1]-view.h/2)/targetZoom];clampCamera()}
function home(){targetZoom=clamp(Math.min(view.w/2050,view.h/1140),.25,.8);targetCamera=[view.w<600?710:1020,655];changed()}
function overview(){targetZoom=clamp(Math.min((view.w-32)/2500,(view.h-24)/1500),.18,.8);targetCamera=[1250,750];changed()}
function resize(){const r=room.getBoundingClientRect();view.w=Math.max(1,r.width);view.h=Math.max(1,r.height);view.dpr=Math.min(window.devicePixelRatio||1,3);canvas.width=Math.round(view.w*view.dpr);canvas.height=Math.round(view.h*view.dpr)}
function hitBook(p){return model.rects().reverse().find(r=>r.id!==view.selected&&contains(r,p,3))?.id||''}
function hitContainer(p){return Object.keys(model.state.containers).reverse().find(k=>contains(model.containerRect(k),p))||''}
function playSound(){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});const t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(190,t);o.frequency.exponentialRampToValueAtTime(95,t+.11);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.06,t+.006);g.gain.exponentialRampToValueAtTime(.001,t+.16);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.17);o.onended=()=>{o.disconnect();g.disconnect()}}catch{}}
function completeMove(ok,message){if(!ok){toast('That space is full. Try another spot.');return false}view.selected='';view.hover='';changed();playSound();toast(message||'A little more at home.');return true}
function drop(p){if(!view.selected)return false;const key=hitContainer(p);if(key)return completeMove(model.move(view.selected,key,model.indexAt(key,p[0],view.selected)),model.state.containers[key].kind==='cart'?'On the cart. Pull its gold handle to take it along.':'Placed. You can arrange things your way.');
 const [cx,cy]=model.state.cart;const blocked=[{x:cx-5,y:cy-145,w:325,h:325},{x:1920,y:735,w:220,h:235},{x:2180,y:895,w:125,h:135}].some(r=>contains(r,p));if(blocked||!model.floor(view.selected,p)){toast('Find a shelf, pile, or clear space on the floor.');return false}return completeMove(true,'A little pile, for later.')}
function cancelGesture(){if(gesture?.kind==='cart'&&!gesture.moved)model.history.pop();gesture=null;view.dragging=false;canvas.classList.remove('dragging');hud()}
function down(e){if(e.button!==undefined&&e.button!==0)return;e.preventDefault();canvas.focus({preventScroll:true});try{canvas.setPointerCapture(e.pointerId)}catch{}const p=point(e);pointers.set(e.pointerId,p);
 if(pointers.size>=2){cancelGesture();const a=[...pointers.values()];pinch={distance:Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]),center:[(a[0][0]+a[1][0])/2,(a[0][1]+a[1][1])/2]};suppress=true;return}
 if(suppress)return;const wp=world(p);view.pointer=wp;let kind='pan';if(view.selected)kind='place';else{const id=hitBook(wp);if(id){view.selected=id;kind='book'}else{const [x,y]=model.state.cart;if(contains({x:x+250,y:y-157,w:75,h:113},wp)){kind='cart';model.checkpoint()}}}
 gesture={kind,start:p,last:p,moved:false,cartOffset:[model.state.cart[0]-wp[0],model.state.cart[1]-wp[1]]};hud()}
function move(e){const p=point(e);if(pointers.has(e.pointerId))pointers.set(e.pointerId,p);view.pointer=world(p);view.hover=view.selected?hitContainer(view.pointer):'';
 if(pointers.size>=2&&pinch){const a=[...pointers.values()],distance=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]),center=[(a[0][0]+a[1][0])/2,(a[0][1]+a[1][1])/2];if(pinch.distance>0)zoom(distance/pinch.distance,center);targetCamera[0]-=(center[0]-pinch.center[0])/targetZoom;targetCamera[1]-=(center[1]-pinch.center[1])/targetZoom;clampCamera();pinch={distance,center};return}
 if(!gesture||suppress||!pointers.has(e.pointerId))return;const g=gesture;if(Math.hypot(p[0]-g.start[0],p[1]-g.start[1])>7)g.moved=true;
 if(g.kind==='pan'||(g.kind==='place'&&g.moved)){targetCamera[0]-=(p[0]-g.last[0])/view.zoom;targetCamera[1]-=(p[1]-g.last[1])/view.zoom;clampCamera()}
 else if(g.kind==='cart'&&g.moved){const wp=world(p);model.moveCart([wp[0]+g.cartOffset[0],wp[1]+g.cartOffset[1]]);changed()}
 view.dragging=g.kind==='book'&&g.moved;canvas.classList.toggle('dragging',g.moved);g.last=p}
function up(e){const p=point(e);pointers.delete(e.pointerId);if(suppress){if(!pointers.size){suppress=false;pinch=null;cancelGesture()}return}const g=gesture;if(!g)return;
 if((g.kind==='book'&&g.moved)||(g.kind==='place'&&!g.moved)){if(p[0]>=0&&p[0]<=view.w&&p[1]>=0&&p[1]<=view.h)drop(world(p));else toast('Still holding your book. Tap a place in the room.')}
 else if(g.kind==='book')toast('Book in hand. Tap a place, or drag empty space to explore.');
 else if(g.kind==='cart'){if(g.moved){changed();toast('Your books came along.')}else model.history.pop()}
 else if(g.kind==='pan'&&!g.moved){const key=hitContainer(world(p));if(key&&model.state.containers[key].kind==='shelf'){const r=model.containerRect(key);targetCamera=[r.x+r.w/2,r.y+r.h/2];targetZoom=clamp(Math.min((view.w-100)/r.w,(view.h-50)/r.h),.5,3.6);clampCamera()}}
 gesture=null;view.dragging=false;canvas.classList.remove('dragging');hud()}
canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);cancelGesture();if(!pointers.size){suppress=false;pinch=null}persist()});canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(Math.exp(-clamp(e.deltaY,-150,150)*.002),point(e))},{passive:false});
function undo(){cancelGesture();view.selected='';if(model.undo()){changed();toast('Back to where it was.')}else toast('Nothing to undo yet.')}
$('undo').onclick=undo;$('home').onclick=home;$('overview').onclick=overview;$('zoom-in').onclick=()=>zoom(1.25);$('zoom-out').onclick=()=>zoom(.8);$('put-back').onclick=()=>{view.selected='';hud()};$('hints').onclick=()=>{view.hints=!view.hints;hud()};$('sound').onclick=()=>{sound=!sound;hud();playSound()};$('help').onclick=()=>$('help-dialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
function fillBookList(){const current=$('choose-book').value;$('choose-book').replaceChildren();for(const b of Object.values(model.state.books)){const option=document.createElement('option');option.value=b.id;option.textContent=`${CATEGORIES[b.category]} · ${b.title} · Vol. ${b.volume}`;$('choose-book').append(option)}if(model.state.books[current])$('choose-book').value=current;$('choose-place').replaceChildren();for(const key of Object.keys(model.state.containers)){const o=document.createElement('option');o.value=key;o.textContent=model.description(key);$('choose-place').append(o)}}
$('book-list').onclick=()=>{fillBookList();$('list-message').textContent='Choose any arrangement that feels right.';$('books-dialog').showModal()};$('place-book').onclick=()=>{const id=$('choose-book').value,key=$('choose-place').value,index=Number($('choose-position').value);if(!model.move(id,key,index)){$('list-message').textContent='That space is full. Try another destination.';return}view.selected='';changed();playSound();$('list-message').textContent='Placed. Your room has been updated.';fillBookList()};
window.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea')||document.querySelector('dialog[open]'))return;if(e.key==='Escape'){view.selected='';cancelGesture();hud()}else if(e.key.toLowerCase()==='z'){e.preventDefault();undo()}else if(e.key.toLowerCase()==='h')home();else if(e.key==='+'||e.key==='=')zoom(1.25);else if(e.key==='-')zoom(.8);else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();targetCamera[0]+=(e.key==='ArrowLeft'?-1:e.key==='ArrowRight'?1:0)*100/targetZoom;targetCamera[1]+=(e.key==='ArrowUp'?-1:e.key==='ArrowDown'?1:0)*100/targetZoom;clampCamera()}});
window.addEventListener('pagehide',persist);window.addEventListener('blur',()=>{pointers.clear();suppress=false;pinch=null;cancelGesture();persist()});document.addEventListener('visibilitychange',()=>{if(document.hidden)persist()});new ResizeObserver(resize).observe(room);resize();if(load==='new'){home();view.camera=[...targetCamera];view.zoom=targetZoom}hud();toast(load==='new'?'A room to make your own. One book at a time.':load==='recovered'?'Your room was recovered from its backup.':'Welcome back. Everything is where you left it.');changed();
function tick(time){const dt=Math.min((time-lastTime)/1000||.016,.05);lastTime=time;const alpha=reduced?1:1-Math.exp(-dt*16);view.camera=view.camera.map((n,i)=>n+(targetCamera[i]-n)*alpha);view.zoom+=(targetZoom-view.zoom)*alpha;
 if(view.dragging&&gesture){const p=gesture.last,dx=p[0]<30?-1:p[0]>view.w-30?1:0,dy=p[1]<25?-1:p[1]>view.h-25?1:0;if(dx||dy){targetCamera[0]+=dx*dt*320/view.zoom;targetCamera[1]+=dy*dt*320/view.zoom;clampCamera();view.pointer=world(p)}}renderer.render(model,view);frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick);
// Structured actions share the exact model and commits used by the visible controls.
if(document.modelContext?.registerTool){const life=new AbortController(),register=t=>{try{Promise.resolve(document.modelContext.registerTool(t,{signal:life.signal})).catch(()=>{})}catch{}};
 register({name:'read_library',description:'Read the current books, containers and physical arrangement.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>model.snapshot()});
 register({name:'place_library_book',description:'Move a book into a shelf, cart tray or existing pile and save the room.',inputSchema:{type:'object',properties:{bookId:{type:'string'},containerId:{type:'string'},index:{type:'integer',minimum:-1}},required:['bookId','containerId'],additionalProperties:false},execute:input=>{if(!input||typeof input.bookId!=='string'||typeof input.containerId!=='string'||(input.index!==undefined&&!Number.isInteger(input.index)))throw Error('Invalid book placement');if(!model.move(input.bookId,input.containerId,input.index??-1))throw Error('Unknown book, unknown destination, or no room');view.selected='';hud();const saved=persist();return{bookId:input.bookId,containerId:model.location(input.bookId),saved,shelved:model.count()}}});window.addEventListener('pagehide',()=>life.abort(),{once:true})}
})();
